@HelpDesk.Api_HostAddress = http://localhost:1337

GET {{HelpDesk.Api_HostAddress}}/status
Accept: application/json

### 

POST {{HelpDesk.Api_HostAddress}}/issues
Content-Type: application/json

{
    "software": "8398398",
    "description": "Thing broke"
}
